version: '3.4'

services:
  pizzastorage:
    image: ${DOCKER_REGISTRY-}pizzastorage
    build:
      context: .
      dockerfile: PizzaStorage/Dockerfile
    ports:
      - "80:80"

  database:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"